### ISSUE TITLE
通过gnss和街道数据是否能用来修正IMU朝向？

### ISSUE THREAD

**Issue by kris-w-dev** [robosu12/imu_data_simulation#1]
通过gnss和街道数据是否能用来修正IMU朝向？

**Comment by robosu12** [comment]
在位姿估计中IMU往往不会单独使用，而是通过和camera、lidar等融合，gnss、街道数据均可以作为观测进行修正；

**Comment by robosu12** [comment]
> 通过gnss和街道数据是否能用来修正IMU朝向？
在位姿估计中IMU往往不会单独使用，而是通过和camera、lidar等融合，gnss、街道数据均可以作为观测进行修正；
